### PR TITLE
Nix: fix build with Nix 2.8.0

### PR DESCRIPTION
**Pull request by bobby285271**
Try to reflect the changes made before ~~https://github.com/NixOS/nix/commit/ffe155abd36366a870482625543f9bf924a58281~~ https://github.com/NixOS/nix/commit/69c6fb12eea414382f0b945c0d6c574c43c7c9a3. Without the change the build fails with:

```
In file included from ../backends/nix/nix-lib-plus.cc:27:
../backends/nix/nix-lib-plus.hh:20:107: error: 'string' does not name a type; did you mean 'nString'?
   20 | bool createUserEnv(EvalState & state, DrvInfos & elems, const Path & profile, bool keepDerivations, const string & lockToken);
      |                                                                                                           ^~~~~~
      |                                                                                                           nString
```

Tested compilation on ~~https://github.com/NixOS/nixpkgs/commit/eeab10bd54e2f6a25c27059290e7e7f2b3fd1cf0~~ https://github.com/NixOS/nixpkgs/commit/b57126a16e9a70fc763b517ad45bf5f16f9e4dab. See commit message for lists of related upstream changes.

@matthewbauer @jtojnar Please take a look if you have time, thanks! (we are currently pinning nix to 2.6 in https://github.com/NixOS/nixpkgs/pull/163500)

### CODE REVIEW

**Comment by bobby285271** [comment]
Pushed more updates, did not really tested but it compiles

**Comment by matthewbauer** [comment]
Looks good to me! I can merge it if you think it's ready.

**Comment by bobby285271** [comment]
Just did some trivial testing and I guess I am happy with the current changes, thanks!

I filed https://github.com/NixOS/nixpkgs/pull/169888.
